runtime: nodejs14
env: standard
service: afip-api
instance_class: F2

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  FLAVOR: "prod"
  CERT_FOLDER: "./cert/production"
  MONGO_DB: "afip1"
  DATABASE_NAME: "production"
  AFIP_CUIT: 30716964244
  VERSION: "afip/v1"
  "MONGO_USER": "gary"
  "MONGO_CONNECT": "vegvisir1997"